# Generated by Django 4.2.24 on 2025-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
