# Generated by Django 4.2.24 on 2025-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0002_product_categoria_product_descuento_product_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='galeria',
            field=models.ManyToManyField(blank=True, related_name='products', to='contable.galeria'),
        ),
    ]
