# Generated by Django 4.2.24 on 2025-09-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0003_galeria_product_imagen_product_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
