# Generated by Django 4.2.24 on 2025-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0004_alter_product_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductContsble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(default='General', max_length=50)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='galeria',
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
