# Generated by Django 4.2.24 on 2025-09-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='image',
            new_name='galeria',
        ),
    ]
