# Generated by Django 4.2.24 on 2025-09-24 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_image_galeria_galeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productstore',
            name='galeria',
        ),
        migrations.AddField(
            model_name='galeria',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.productstore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstore',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
