# Generated by Django 4.2.24 on 2025-10-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_proveedor_productstore_price_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cedulaOnita',
            field=models.CharField(default=1252122, max_length=20),
            preserve_default=False,
        ),
    ]
