# Generated by Django 4.2.24 on 2025-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_proveedor_cedulaonita'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
