# Generated by Django 4.2.24 on 2025-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_pedido_admin_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del bono (ej: DESCUENTO50, NAVIDAD2025)', max_length=50, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción del bono para uso interno', max_length=200)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Valor Fijo')], default='porcentaje', max_length=10)),
                ('valor_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o valor fijo en pesos', max_digits=10)),
                ('valor_minimo_compra', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo de compra para aplicar el descuento', max_digits=10)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora desde cuando es válido el bono')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora hasta cuando es válido el bono')),
                ('usos_maximos', models.PositiveIntegerField(default=1, help_text='Número máximo de veces que se puede usar este código')),
                ('usos_realizados', models.PositiveIntegerField(default=0, help_text='Número de veces que ya se ha usado este código')),
                ('activo', models.BooleanField(default=True, help_text='Si el bono está activo o desactivado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bono de Descuento',
                'verbose_name_plural': 'Bonos de Descuento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nota',
            field=models.TextField(blank=True, help_text='Nota del cliente al hacer el pedido', null=True),
        ),
    ]
