# Generated by Django 3.2.25 on 2025-11-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_conversation_conversationmessage_verificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('stock_available', 'Producto Disponible'), ('price_drop', 'Bajada de Precio'), ('back_in_stock', 'Regreso en Stock'), ('low_stock', 'Stock Bajo')], default='stock_available', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Falló')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notify_price_drop', models.BooleanField(default=False)),
                ('target_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('notify_low_stock', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='core.productstore')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.simpleuser')),
            ],
            options={
                'verbose_name': 'Notificación de Stock',
                'verbose_name_plural': 'Notificaciones de Stock',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'email', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('email_subject', models.CharField(max_length=200)),
                ('stock_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stocknotification')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-sent_at'],
            },
        ),
    ]
