# Generated by Django 3.2.25 on 2025-11-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('contraentrega', 'Contra entrega'), ('recoger_tienda', 'Recoger en tienda'), ('tarjeta', 'Tarjeta de crédito/débito'), ('wompi', 'Pago Wompi')], default='contraentrega', max_length=20),
        ),
    ]
