# Generated by Django 3.2.25 on 2025-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_entrega',
            field=models.CharField(choices=[('domicilio', 'Entrega a Domicilio'), ('tienda', 'Recoger en Tienda')], default='domicilio', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Pago en Efectivo'), ('tarjeta', 'Tarjeta de crédito/débito')], default='efectivo', max_length=20),
        ),
    ]
