# Generated by Django 3.2.25 on 2025-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_forma_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('contraentrega', 'Contra Entrega (Efectivo)'), ('recoger_tienda', 'Recoger en Tienda (Efectivo)'), ('tarjeta', 'Tarjeta de crédito/débito'), ('wompi', 'Pago Wompi'), ('efectivo', 'Pago en Efectivo')], default='efectivo', max_length=20),
        ),
    ]
