# Generated by Django 3.2.25 on 2025-11-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('planning', 'En Planificación'), ('development', 'En Desarrollo'), ('testing', 'En Pruebas'), ('completed', 'Completado'), ('paused', 'Pausado')], default='planning', max_length=20, verbose_name='Estado')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen Principal')),
                ('screenshot_1', models.ImageField(blank=True, null=True, upload_to='projects/screenshots/', verbose_name='Captura 1')),
                ('screenshot_2', models.ImageField(blank=True, null=True, upload_to='projects/screenshots/', verbose_name='Captura 2')),
                ('screenshot_3', models.ImageField(blank=True, null=True, upload_to='projects/screenshots/', verbose_name='Captura 3')),
                ('frontend_tech', models.CharField(help_text='Ej: React, Vue.js, Bootstrap', max_length=300, verbose_name='Tecnología Frontend')),
                ('backend_tech', models.CharField(help_text='Ej: Django, Node.js, Python', max_length=300, verbose_name='Tecnología Backend')),
                ('database', models.CharField(help_text='Ej: PostgreSQL, MySQL, MongoDB', max_length=200, verbose_name='Base de Datos')),
                ('authentication', models.CharField(help_text='Ej: JWT, OAuth, Django Auth', max_length=200, verbose_name='Sistema de Autenticación')),
                ('main_components', models.TextField(help_text='Separa cada componente con una línea', verbose_name='Componentes Principales')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('project_url', models.URLField(blank=True, verbose_name='URL del Proyecto')),
                ('github_url', models.URLField(blank=True, verbose_name='Repositorio GitHub')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Proyecto Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-order', '-created_at'],
            },
        ),
    ]
