# Generated by Django 3.2.25 on 2025-11-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20251124_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevisit',
            name='visit_type',
            field=models.CharField(choices=[('store', 'Store Homepage'), ('product_detail', 'Product Detail')], default='store', max_length=20),
        ),
    ]
