# Generated by Django 3.2.25 on 2025-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_storevisit_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevisit',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
