# Generated by Django 3.2.25 on 2025-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20251126_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storevisit',
            name='visit_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('store', 'Store/Tienda'), ('product_detail', 'Product Detail'), ('checkout', 'Checkout/Pago')], default='store', max_length=20),
        ),
    ]
