# Generated by Django 3.2.25 on 2025-11-29 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_storevisit_visit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone', models.CharField(help_text='Formato: +57XXXXXXXXXX (incluir código de país)', max_length=20, verbose_name='Número WhatsApp Admin')),
                ('notify_new_order', models.BooleanField(default=True, verbose_name='Notificar Nuevos Pedidos')),
                ('notify_status_change', models.BooleanField(default=True, verbose_name='Notificar Cambios de Estado')),
                ('notify_low_stock', models.BooleanField(default=False, verbose_name='Notificar Stock Bajo')),
                ('message_template', models.TextField(default='🛒 *Nuevo Pedido #{order_id}*\n\n👤 Cliente: {customer_name}\n📞 Teléfono: {customer_phone}\n💰 Total: ${total}\n📦 Método: {payment_method}\n📍 Dirección: {address}\n\n¡Revisa el dashboard para más detalles!', help_text='Variables disponibles: {order_id}, {customer_name}, {customer_phone}, {total}, {payment_method}, {address}', verbose_name='Plantilla de Mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activar Notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuración WhatsApp',
            },
        ),
    ]
