# Generated by Django 3.2.25 on 2025-11-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Wompi', max_length=100)),
                ('public_key', models.CharField(max_length=200)),
                ('private_key', models.CharField(max_length=200)),
                ('environment', models.CharField(choices=[('production', 'Producción'), ('test', 'Pruebas')], default='production', max_length=20)),
                ('base_url', models.CharField(default='https://production.wompi.co/v1', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
