# Generated by Django 3.2.25 on 2025-11-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_storeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wompiconfig',
            name='integrity_secret',
            field=models.CharField(blank=True, help_text='Clave secreta de integridad de Wompi', max_length=200, null=True),
        ),
    ]
