# Generated by Django 3.2.25 on 2025-11-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_wompiconfig_integrity_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='wompiconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activar/desactivar Wompi como método de pago', verbose_name='Activar Wompi'),
        ),
    ]
