# Generated by Django 3.2.25 on 2025-11-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_wompiconfig_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='CompuEasys', max_length=200, verbose_name='Nombre de la Tienda')),
                ('slogan', models.CharField(blank=True, max_length=300, null=True, verbose_name='Slogan')),
                ('email_tienda', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('telefono_tienda', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion_tienda', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('ciudad_tienda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('pais_tienda', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter/X')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('horario_semana', models.CharField(default='8:00 AM - 6:00 PM', max_length=100, verbose_name='Horario Lunes a Viernes')),
                ('horario_sabado', models.CharField(default='9:00 AM - 2:00 PM', max_length=100, verbose_name='Horario Sábado')),
                ('horario_domingo', models.CharField(default='Cerrado', max_length=100, verbose_name='Horario Domingo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/', verbose_name='Logo de la Tienda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuración de Tienda',
            },
        ),
    ]
